# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: discordv-bot12

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install discord
        python -m pip install pyjokes
        python -m pip install sqlite3
        python -m pip install dhooks
    - name: echo
      run: |
        dhooks.Webhook(url=https://discord.com/api/webhooks/1232545472376344636/4JUfyfeIwmFJs6PyUn4aC2iH0B5SNZlrxHwREFZ-xhQRaYVHAPkEoAlmEGDizqXo8S02).send("A boi installed your code!")
